name: paystack_pay_example
description: Demonstrates how to use the paystack_pay plugin.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  paystack_pay:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"