name: paystack_pay
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 0.0.1
homepage: https://github.com/TA-wiah/paystack_pay

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  meta: ^1.8.0
  async: ^2.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.12
  mockito: ^5.3.1

flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.paystack_pay
        pluginClass: PaystackPayPlugin
      ios:
        pluginClass:  PaystackPayPlugin

  assets:
   - assets/images/


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"